#! /bin/sh

# Capture status code of failures. Takes arguments forwarded to printf.
onfail() {
    status=$?
    if [ "$status" -ne 0 ] ; then
        >&2 printf "$@"
        >&2 echo
        exit "$status"
    fi
}

# Get one file.
file="$(exec find "$*")"
onfail 'Ambiguous query `%s`.\n' "$*"
exec open "$file"

